sudo: false
dist: trusty
language: node_js

node_js:
- '6'

addons:
  ssh_known_hosts: web.teiler.io
  apt:
    packages:
    - google-chrome-stable

cache:
  yarn: true
  directories:
    - node_modules

before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3

install:
- yarn install

before_script:
- ng lint

script:
- ng test --single-run
- ng e2e
- ng build --prod

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master
