language: node_js

node_js:
- '6'

install:
- cd backend && npm i --test && cd ..
- cd frontend && npm i --test && cd ..

before_install:
- openssl aes-256-cbc -K $encrypted_46ef87e06650_key -iv $encrypted_46ef87e06650_iv
  -in .travis/deploy_key.pem.enc -out .travis/deploy_key.pem -d

before_deploy:
- .travis/build.sh

deploy:
  - provider: script
    script: .travis/deploy.sh
    skip_cleanup: true
    on:
      branch: master

notifications:
  webhooks:
    urls:
    - https://fathomless-fjord-24024.herokuapp.com/notify?secret=JOuQI5jyJE4Du6RmVpMvAqgMVvTskbgNErHbiZ0cL89TrOLTHX
    on_success: change
    on_failure: always