language: node_js
node_js:
 - "6"
 
 # install dev dependencies
install:
 - cd backend && npm i --test && cd ..
 - cd frontend && npm i --test && cd ..

# check code quality
before_script:
 # lint backend code
 #- cd backend && npm run lint && cd ..
 # lint frontend code
 #- cd frontend-src && npm run lint && cd ..

# run unit tests
script:
 # - cd backend && npm test && cd ..

# delete dev dependencies after success
after_success:
  - cd backend && rm -rf node_modules && cd ..
  - cd frontend && rm -rf node_modules && cd ..

before_deploy:
  # build frontend into backend/public
  - cd frontend
  - npm install
  - ng build --prod
  
    # build backend
  - cd ../backend
  
notifications:
  webhooks: 
    urls:
      - https://fathomless-fjord-24024.herokuapp.com/notify?secret=JOuQI5jyJE4Du6RmVpMvAqgMVvTskbgNErHbiZ0cL89TrOLTHX
    on_success: change # default: always
    on_failure: always # default: always
